### ISSUE TITLE
Prices refetched on every run

### ISSUE THREAD

**Issue by jhoogstraat** [provinzio/CoinTaxman#114] opened 2022-03-24 01:37 UTC
All prices are refetched every time the program is started.

This can take quite some time and I thought that's what the database is for.

**Comment by provinzio** [comment] 2022-03-24 06:10
Nothing should be refetched from the API when a price for the correct timestamp exists in the database. 

Only the prices from csv are checked on every run, but this shouldn't take long. 

Virtual sells are fetched on every run, because they represent the sell of all coins at runtime. You can deactivate the virtual sell option in config.

**Comment by Griffsano** [comment] 2022-03-25 21:46
Can your problem be resolved by setting `CALCULATE_VIRTUAL_SELL = False` in `config.ini`?
If not, it might be because the table names are not sorted in the `get_price_db` function, hence the prices for some pairs cannot be found in the database and are fetched again. This should be resolved by https://github.com/provinzio/CoinTaxman/pull/106.

**Comment by jhoogstraat** [comment] 2022-03-26 00:21
I did set it to False, but prices are refetched still... I'll try #106

**Comment by Griffsano** [comment] 2022-03-26 12:34
Hmm, that error should actually be caught. Could you provide more logging info (where this error is raised in the code) and maybe also the DIA/USDT lines of the export CSV that lead to this error (including header of the CSV). You can replace confidential info like username, timestamp, amount of DIA/USDT etc.

**Comment by Griffsano** [comment] 2022-03-26 12:52
Before you do that, you could try one thing: Replace line 330 in database.py
https://github.com/provinzio/CoinTaxman/blob/b97353017d6238481e7810c857ff83c0c5c89001/src/database.py#L330
by this and see if the error is resolved:
`if f"UNIQUE constraint failed: {tablename}.utc_time" in str(e):`

**Comment by jhoogstraat** [comment] 2022-03-26 13:21
I'll try the code change first and then report the affecting lines.

Notice: I have to change a line in my statement, because of a crypto deposit, which would otherwise result in an "unmatched buy/sell positions". It does not work yet, but I changed:
```
86550091,2021-04-03 16:04:05,Spot,Deposit,EOS,31.20000000,""
```
to
```
86550091,2021-04-03 16:00:00,Spot,Deposit,EUR,164,""
86550091,2021-04-03 16:04:05,Spot,Buy,EOS,31.20000000,""
86550091,2021-04-03 16:04:05,Spot,Transaction Related,EUR,-164,""
```
which results in the error mentioned.

**Comment by Griffsano** [comment] 2022-03-26 14:14
Ah ok, I see. The problem is not `UNIQUE constraint failed`, it's the zero price. This can be easily fixed.
However, the price fetching for `DIABTC` looks weird to me, I think this should not happen. Could you share the CSV entries for 2021-04-11 01:02:30+00:00?

**Comment by jhoogstraat** [comment] 2022-03-26 15:50
Sorry, forgot those:
```
86550091,2021-04-11 01:02:30,Spot,Small assets exchange BNB,DIA,-0.00031280,""
```

**Comment by Griffsano** [comment] 2022-03-26 16:33
I made some fixes, could you try out the newest commit from #106?

**Comment by jhoogstraat** [comment] 2022-03-26 18:29
That does make the error go away. Is setting the price to 0 not skewing with the result?

**Comment by Griffsano** [comment] 2022-03-26 19:19
Yes, exactly. But now it should not be zero anymore, could you check this? For example, by adding this line after line 112:
https://github.com/provinzio/CoinTaxman/blob/b97353017d6238481e7810c857ff83c0c5c89001/src/database.py#L112
`print("DB price: ", price)`

If the database price is still zero, then I could not reproduce the problem. I think this is what happened:
As far as I could reproduce the problem, the price zero was written in your database for some reason (`price_db`). Once it's written in the database, it usually stays and is not overwritten (except for when a new price is found in the CSVs). With the quick fix that I implemented now, the price in the database (`price_db`) is automatically overwritten if it's zero, even if the source is not the CSV export. However, this logic also overwrites the DB price if the new price (`price`) is zero, so it's not the cleanest way to do this and no final solution.

**Comment by jhoogstraat** [comment] 2022-03-26 19:47
That makes sense, and I agree that this is what happened. Binance does not provide a price for DIA/EUR, nor DIA/USDT for the timeframe, so the price cannot be set (checked the [api](https://api.binance.com/api/v3/aggTrades?symbol=DIAUSDT&startTime=1618102920000&endTime=1618102980000))

**Comment by Griffsano** [comment] 2022-03-26 19:55
It appears that once the price fetching falls back to USDT/USDT, zero is written in the DB:
https://github.com/provinzio/CoinTaxman/blob/b97353017d6238481e7810c857ff83c0c5c89001/src/price_data.py#L130-L131

**Comment by jhoogstraat** [comment] 2022-03-26 20:02
Which is a PR by myself, coincidentally :P

I even wrote a check_database function to see if any entries are 0 and tries to fix them.

**Comment by Griffsano** [comment] 2022-03-26 20:19
We could use a similar approach as for other exchanges (e.g. Kraken), where the time window is moved to the past if no trade can be found, until the last traded price is evaluated. Since no trades occurred in the meantime, the price should still be valid.

Another question is what to do with the (erroneous) zero price entries in the databases? Even if we implement a backup solution (like the time window shifting), the zero entries remain in the database and won't get overwritten in the future. To overcome this, I suggest that we add a logic in #106 that automatically overwrites zero entries if the new price data is nonzero.

What do you think of this?

**Comment by jhoogstraat** [comment] 2022-03-26 20:33
Seems sensible.
I don't see a reason why we should not implement an automatic fixing for zero entries with the backup solution, as new entries would receive the same treatment from the beginning.

**Comment by provinzio** [comment] 2022-03-26 23:16
Feel free to checkout #16 which might help you here. It fetches all coins and decides by shortest oath algorithm which coins pairs are used to calculate the fiat price. 

Might work, because it's not only relying on BTC and usdt.

**Comment by jhoogstraat** [comment] 2022-03-27 09:54
Really looking forward your pr!
Are you planning to rebase your changes onto current main in the near future? There are some merge conflicts currently.

Still, we need to handle 0 entries which are already present in the database. I guess the new algorithm will work in 99.9% of all cases, so is it worth it to have the timeframe method still?

**Comment by Griffsano** [comment] 2022-03-27 12:44
> Seems sensible. I don't see a reason why we should not implement an automatic fixing for zero entries with the backup solution, as new entries would receive the same treatment from the beginning.

Yes, we could do this as database patch. Ok, then I'll not implement any zero price catching function in #106 for now.

> Still, we need to handle 0 entries which are already present in the database. I guess the new algorithm will work in 99.9% of all cases, so is it worth it to have the timeframe method for all exchanges?

I think it will be worth it to have it as backup solution. Also, it shouldn't be that much work, as we can re-use the concept from e.g. Kraken.

**Comment by provinzio** [comment] 2022-04-08 21:26
Should be fixed. :)

**Closed by provinzio** 2022-04-08 21:26 UTC
